### ISSUE TITLE
develop assessments

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-lessons#1]
_From @mbjones on January 26, 2017 22:31_

Need pre-, mid-, and post- training assessments instruments, which could/should be compatible with prior years.  To publish on these, we'll also need UCSB IRB approval.
- [x] Pre-course assessment
- [x] Mid-course assessment (focused on course correction feedback)
- [x] Post-course assessment
- [x] IRB application

We also could consider doing a followup on the 2014 and 2013 course to gauge the impact of those courses on career trajectories.

_Copied from original issue: NCEAS/oss-2017#2_

**Comment by mbjones** [comment]
_From @brunj7 on January 27, 2017 3:1_

I gave you access to the Google forms we used for the SNAPP training; it is based on what Stacy did for previous OSS. Feel free to use this as starting point if you go with Google forms: 

Pre:
https://docs.google.com/a/nceas.ucsb.edu/forms/d/1U1f63UNi0MrOpp7BzlTXY1MbjEtjQnJf8eR13soSKgE/edit?usp=sharing

Post (never used it):
https://docs.google.com/a/nceas.ucsb.edu/forms/d/1xUx4ujNTtmWyRIItiYd6UdzabQdSVE3OCGAGgXynR8M/edit?usp=sharing

**Comment by mbjones** [comment]
_From @aebudden on January 27, 2017 4:25_

Thanks Julien.  I'll connect with Stacy too since I believe there was a mid-term evaluation done.

**Comment by mbjones** [comment]
_From @cjlortie on January 27, 2017 20:25_

I would be keen to see previous evaluations. I can set up private repo for data, and I would love to even a bit of EDA & Viz on it. Could use this repo: https://github.com/cjlortie/OSS2017

**Comment by aebudden** [comment]
Previous assessment results have been shared with @cjlortie @mbjones and @aebudden via email. Assessments have been modified to reflect the details of this course and submitted to HSC for IRB approval.
