### ISSUE TITLE
Pre-arrival checklist for participants

### ISSUE THREAD

**Issue by aebudden** [NCEAS/oss-lessons#10]
I need to send out a pre-arrival email to all participants with a list of what they need to bring, travel logistics etc.  Please can you add to this ticket any software you would like them to have pre-installed (please provide links) and any other information / material / resources they will need for the subjects you are teaching.

**Comment by aebudden** [comment]
From call with Matt:
SSH client - recommendations for windows and mac
Text editor

@amoeba Bryce - Matt suggested you might be the best person to start this list? He also suggested creating a md page in the OSS-2017 that the participants can reference once the list is finalized.

**Comment by amoeba** [comment]
Yeah I can start this. A page sounds good. I'll start this up and notify back here.

**Comment by amoeba** [comment]
IIRC, we were aiming to have most all of the work done via RStudio Server (web browser) or on a VM (via SSH), so I've made a note of that. As instructors, we'll need to get various dependencies pre-installed system-wide so the students will have access to them without needing to install anything. I'll make a separate issue.

I've started the page, though it isn't linked into the navbar, you can read the rendered output [here](https://nceas.github.io/oss-2017/before.html).

**Comment by amoeba** [comment]
- [ ] Need to decide on a text editor for users in case they need to edit a text or program code file locally.
