### ISSUE TITLE
Prepare remote server (Aurora)? with all software deps needed for lessons

### ISSUE THREAD

**Issue by amoeba** [NCEAS/oss-lessons#11]
Most of the work students will do is going to be on Aurora (I think) via RStudio and SSH. Therefore, all lessons will need their dependencies installed system-wide (by nick or someone else) prior to the workshop and someone (me) will need to run through them all to make sure students can run/do everything.

**Comment by mbjones** [comment]
I'm pretty sure this is complete. Let us know if more packages are needed.
