### ISSUE TITLE
Set up Google Drive for the participants

### ISSUE THREAD

**Issue by brunj7** [NCEAS/oss-lessons#12]
- [x] Set up the Drive using the NCEAS WG account
- [x] Add the Readme
- [x] Ask Nick for a human readable redirect

**Comment by brunj7** [comment]
Google Drive: https://drive.google.com/drive/u/0/folders/0B8o4yO5uV6GLTlEyWFpmV1FPZkU

README: https://docs.google.com/document/d/1zxFEzNERsmKz371ZTUEoeRZKQNWYUDCTTmLMmw7mePc/edit#

**Comment by zenrabbit** [comment]
Thanks jb!
