### ISSUE TITLE
My running list of packages for mon-tues spatial lessons

### ISSUE THREAD

**Issue by lwasser** [NCEAS/oss-lessons#21]
This isn't complete YET - but i'll add to it here and then they can be checked on aurora.

- [x] raster (sp installed as a dependency of raster)
- [x] rgdal
- [x] ncdf4
- [x] rhdf5 (bioconductor)
- [x] ggplot2 (i need to check but i think we want the dev install from GH rather than cran
- [x] ggmap (same as above - will check)
- [x] utils (part of base i think?)
- [x] rgeos
- [x] tmap
- [x] mapview

i presume that GDAL libraries and H5 libraries are installed on aurora -- we will know once the libraries are installed. I've never had a problem with them just let's check.

**Comment by mbjones** [comment]
We have `ncdf` and `ncdf4`, but not `netcdf4` -- I'll add that along with the others that I didn't check here.

**Comment by lwasser** [comment]
fixed -- `ncdf4` is what we need

**Comment by mbjones** [comment]
All installed.  Reopen the ticket if you have more that needs installing.

**Comment by lwasser** [comment]
awesome - thanks so much @mbjones
