### ISSUE TITLE
Call 06/02 - notes

### ISSUE THREAD

**Issue by brunj7** [NCEAS/oss-lessons#8]
## Discussed on call 06/02

Code of conduct for participants: help to build community and exchanges

To do list :

- [x] assessment poll again now.  everyone gets to participate
- [x] share current poll data with instructors 
- [ ] Plan outcomes collectively in a google doc 
- [ ] sample datasets we all try to work with or at least limit the number of different case studies 
- [ ] Code of conduct 
- [x] deadline for outcomes and objectives at least 
- [ ] Make an instructor-level list of tools we expect students to have installed and or server setup
- [ ] Identify one co-instructor for your lesson.

**Comment by zenrabbit** [comment]
Thank you Julien. I shared the current poll data via slack but here is repo I used to wrangle and identify an excellent pool of participants to teach and work with for this iteration of OSS.
https://cjlortie.github.io/ninja.skills.score/
I nonetheless reviewed all applicants in detail to ensure that a quantitative approach was not sensitive to reporting biases within the application poll.

**Comment by zenrabbit** [comment]
On the OSS calendar, we set the deadline of June 19th for taking a first crack at your learning outcomes.

**Comment by zenrabbit** [comment]
The assessment poll is now set up.  Please jump in and add your Qs.

**Comment by aebudden** [comment]
I can address the code of conduct.  This is something that should be established at the beginning of a collaboration and so we can include it in the session on expectations.

**Comment by aebudden** [comment]
Tools list moved to its own ticket (https://github.com/NCEAS/oss-lessons/issues/10). Please can instructors add their requirements to that issue.
